import Link from 'next/link'
import { Inter, Noto_Sans_KR } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

const notoSansKr = Noto_Sans_KR({
  subsets: ['latin'],
  weight: ['100', '400', '700', '900']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const menus = ['All Posts', 'My Story', 'Frontend', 'JavaScript']

  return (
    <aside className='w-32 flex flex-col self-end'>
      <h2 className='text-lg' >Category</h2>
      <ul className='text-sm'>
        {
          menus.map( menu => {
            return <li>{menu}</li>
          })
        }
      </ul>
    </aside>
  )
}
