import Link from 'next/link'
import './globals.css'
import { Open_Sans } from 'next/font/google'

import Header from '@/components/Header'
import Footer from '@/components/Footers'

const sans = Open_Sans({ subsets: ['latin'] })



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const menus = ['Home', 'About', 'Posts', 'Contact']

  return (
    <html lang="en" className={sans.className}>
      <body className='flex flex-col w-full mx-auto'>
        <Header/>
        <main className='grow max-w-screen-2xl w-full mx-auto'>
          {children}
        </main>
        <Footer/>
        </body>
    </html>
  )
}
